### ISSUE TITLE
Game crashing on world load

### ISSUE THREAD

**Issue by Cheeseman46** [TelepathicGrunt/Bumblezone-Fabric#29]
Whenever I try to start/load a world the game will crash instantly, i've tried reinstalling the mod, reinstalling fabric, starting a world first before modding and then starting it after modding, etc.

I'm completely stuck

"The game crashed whilst exception in server tick loop
Error: java.lang.ExceptionInInitializerError
Exit Code: -1"

Is what shows up when it crashes

![help](https://user-images.githubusercontent.com/84248539/118376501-dd22e580-b58d-11eb-8a6b-987947b15807.png)

Above is whats in my mods folder

Crash log:

---- Minecraft Crash Report ----
// You're mean.

Time: 5/8/21 5:28 PM
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError
at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.lambda$createEntityComponentContainer$3(CardinalEntityInternals.java:101)
at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals$$Lambda$4697/1627373804.apply(Unknown Source)
at java.util.HashMap.computeIfAbsent(HashMap.java:1118)
at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.createEntityComponentContainer(CardinalEntityInternals.java:86)
at net.minecraft.class_1297.handler$zhb000$initDataTracker(class_1297.java:4185)
at net.minecraft.class_1297.(class_1297.java:263)
at net.minecraft.class_1309.(class_1309.java:219)
at net.minecraft.class_1308.(class_1308.java:125)
at net.minecraft.class_1421.(class_1421.java:10)
at net.minecraft.class_1420.(class_1420.java:40)
at net.minecraft.class_1299$$Lambda$935/2078890030.create(Unknown Source)
at net.minecraft.class_1299.method_5883(class_1299.java:463)
at com.telepathicgrunt.bumblezone.entities.BeeAggression.setupBeeHatingList(BeeAggression.java:55)
at com.telepathicgrunt.bumblezone.Bumblezone.lambda$onInitialize$0(Bumblezone.java:67)
at com.telepathicgrunt.bumblezone.Bumblezone$$Lambda$2445/417383960.onWorldLoad(Unknown Source)
at net.fabricmc.fabric.api.event.lifecycle.v1.ServerWorldEvents.lambda$static$0(ServerWorldEvents.java:34)
at net.fabricmc.fabric.api.event.lifecycle.v1.ServerWorldEvents$$Lambda$2442/143879459.onWorldLoad(Unknown Source)
at net.minecraft.server.MinecraftServer.redirect$zzd000$onLoadWorld(MinecraftServer.java:1781)
at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:369)
at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:335)
at net.minecraft.class_1132.method_3823(class_1132.java:67)
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645)
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
at net.minecraft.server.MinecraftServer$$Lambda$4660/1476963864.run(Unknown Source)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failed to hack fabric API
at dev.onyxstudios.cca.internal.base.ComponentsInternals.(ComponentsInternals.java:56)
... 25 more
Caused by: java.lang.NoSuchFieldException: type
at java.lang.Class.getDeclaredField(Class.java:2070)
at dev.onyxstudios.cca.internal.base.ComponentsInternals.(ComponentsInternals.java:52)
... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
-- System Details --
Details:
Minecraft Version: 1.16.5
Minecraft Version ID: 1.16.5
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1597159976 bytes (1523 MB) / 3019898880 bytes (2880 MB) up to 4294967296 bytes (4096 MB)
CPUs: 16
JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
Fabric Mods:
cardinal-components-base: Cardinal Components API (base) 2.7.10
cardinal-components-entity: Cardinal Components API (entities) 2.7.10
cloth-basic-math: Cloth Basic Math 0.5.1
cloth-config2: Cloth Config v4 4.11.19
fabric: Fabric API 0.34.1+1.16
fabric-api-base: Fabric API Base 0.3.0+c88702897d
fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
fabric-networking-api-v1: Fabric Networking API (v1) 1.0.2+d6244c6d7d
fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
fabricloader: Fabric Loader 0.11.3
java: Java HotSpot(TM) 64-Bit Server VM 8
minecraft: Minecraft 1.16.5
the_bumblezone: The Bumblezone - Fabric 1.16.5-2.4.2
Player Count: 0 / 8; []
Data Packs: vanilla, Fabric Mods
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by TelepathicGrunt** [comment]
Download the latest cardinal components mod. The version I Jar-in-jar into my mod is an older version that doesn’t work with newer fabric api

**Comment by Cheeseman46** [comment]
> Download the latest cardinal components mod. The version I Jar-in-jar into my mod is an older version that doesn’t work with newer fabric api

Thanks, this worked out
